apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: laap-v2
  namespace: laap-v2
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: laap-v2
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60